language: cpp
sudo: required
dist: trusty
compiler:
    - gcc
install:
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq libboost-all-dev openmpi-bin libopenmpi-dev 
    - sudo apt-get install -y -qq cmake 
script: 
    - cd build/release && cmake ../../ -DCMAKE_BUILD_TYPE=Release && make && cd ../../tests && ./run_tests.sh

notifications:
    email:
        recipients: 
            - fzenke@stanford.edu
        on_success: change
        on_failure: always
